package com.schonherz.dbentities;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.schonherz.dbentities.AutoKep;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table Autokepek.
*/
public class AutoKepDao extends AbstractDao<AutoKep, Long> {

    public static final String TABLENAME = "Autokepek";

    /**
     * Properties of entity AutoKep.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property AutoKepID = new Property(0, Long.class, "autoKepID", true, "AUTO_KEP_ID");
        public final static Property AutoKepPath = new Property(1, String.class, "autoKepPath", false, "AUTO_KEP_PATH");
        public final static Property AutoKepDateTime = new Property(2, String.class, "autoKepDateTime", false, "AUTO_KEP_DATE_TIME");
        public final static Property AutoKepIsUploaded = new Property(3, Boolean.class, "autoKepIsUploaded", false, "AUTO_KEP_IS_UPLOADED");
        public final static Property AutoID = new Property(4, Long.class, "autoID", false, "AUTO_ID");
    };

    private DaoSession daoSession;

    private Query<AutoKep> auto_AutoKepListQuery;

    public AutoKepDao(DaoConfig config) {
        super(config);
    }
    
    public AutoKepDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'Autokepek' (" + //
                "'AUTO_KEP_ID' INTEGER PRIMARY KEY ," + // 0: autoKepID
                "'AUTO_KEP_PATH' TEXT," + // 1: autoKepPath
                "'AUTO_KEP_DATE_TIME' TEXT," + // 2: autoKepDateTime
                "'AUTO_KEP_IS_UPLOADED' INTEGER," + // 3: autoKepIsUploaded
                "'AUTO_ID' INTEGER);"); // 4: autoID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'Autokepek'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AutoKep entity) {
        stmt.clearBindings();
 
        Long autoKepID = entity.getAutoKepID();
        if (autoKepID != null) {
            stmt.bindLong(1, autoKepID);
        }
 
        String autoKepPath = entity.getAutoKepPath();
        if (autoKepPath != null) {
            stmt.bindString(2, autoKepPath);
        }
 
        String autoKepDateTime = entity.getAutoKepDateTime();
        if (autoKepDateTime != null) {
            stmt.bindString(3, autoKepDateTime);
        }
 
        Boolean autoKepIsUploaded = entity.getAutoKepIsUploaded();
        if (autoKepIsUploaded != null) {
            stmt.bindLong(4, autoKepIsUploaded ? 1l: 0l);
        }
 
        Long autoID = entity.getAutoID();
        if (autoID != null) {
            stmt.bindLong(5, autoID);
        }
    }

    @Override
    protected void attachEntity(AutoKep entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AutoKep readEntity(Cursor cursor, int offset) {
        AutoKep entity = new AutoKep( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // autoKepID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // autoKepPath
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // autoKepDateTime
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // autoKepIsUploaded
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // autoID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AutoKep entity, int offset) {
        entity.setAutoKepID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAutoKepPath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAutoKepDateTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAutoKepIsUploaded(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setAutoID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AutoKep entity, long rowId) {
        entity.setAutoKepID(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AutoKep entity) {
        if(entity != null) {
            return entity.getAutoKepID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "autoKepList" to-many relationship of Auto. */
    public synchronized List<AutoKep> _queryAuto_AutoKepList(Long autoID) {
        if (auto_AutoKepListQuery == null) {
            QueryBuilder<AutoKep> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.AutoID.eq(autoID));
            auto_AutoKepListQuery = queryBuilder.build();
        } else {
            auto_AutoKepListQuery.setParameter(0, autoID);
        }
        return auto_AutoKepListQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAutoDao().getAllColumns());
            builder.append(" FROM Autokepek T");
            builder.append(" LEFT JOIN Autok T0 ON T.'AUTO_ID'=T0.'AUTO_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AutoKep loadCurrentDeep(Cursor cursor, boolean lock) {
        AutoKep entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Auto auto = loadCurrentOther(daoSession.getAutoDao(), cursor, offset);
        entity.setAuto(auto);

        return entity;    
    }

    public AutoKep loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AutoKep> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AutoKep> list = new ArrayList<AutoKep>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AutoKep> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AutoKep> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
