package com.schonherz.dbentities;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.IdentityScopeType;

import com.schonherz.dbentities.SoforDao;
import com.schonherz.dbentities.ProfilKepDao;
import com.schonherz.dbentities.AutoDao;
import com.schonherz.dbentities.AutoKepDao;
import com.schonherz.dbentities.MunkaTipusDao;
import com.schonherz.dbentities.PartnerDao;
import com.schonherz.dbentities.PartnerKepDao;
import com.schonherz.dbentities.TelephelyDao;
import com.schonherz.dbentities.MunkaEszkozDao;
import com.schonherz.dbentities.MunkaDao;
import com.schonherz.dbentities.MunkaKepDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        SoforDao.createTable(db, ifNotExists);
        ProfilKepDao.createTable(db, ifNotExists);
        AutoDao.createTable(db, ifNotExists);
        AutoKepDao.createTable(db, ifNotExists);
        MunkaTipusDao.createTable(db, ifNotExists);
        PartnerDao.createTable(db, ifNotExists);
        PartnerKepDao.createTable(db, ifNotExists);
        TelephelyDao.createTable(db, ifNotExists);
        MunkaEszkozDao.createTable(db, ifNotExists);
        MunkaDao.createTable(db, ifNotExists);
        MunkaKepDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        SoforDao.dropTable(db, ifExists);
        ProfilKepDao.dropTable(db, ifExists);
        AutoDao.dropTable(db, ifExists);
        AutoKepDao.dropTable(db, ifExists);
        MunkaTipusDao.dropTable(db, ifExists);
        PartnerDao.dropTable(db, ifExists);
        PartnerKepDao.dropTable(db, ifExists);
        TelephelyDao.dropTable(db, ifExists);
        MunkaEszkozDao.dropTable(db, ifExists);
        MunkaDao.dropTable(db, ifExists);
        MunkaKepDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SoforDao.class);
        registerDaoClass(ProfilKepDao.class);
        registerDaoClass(AutoDao.class);
        registerDaoClass(AutoKepDao.class);
        registerDaoClass(MunkaTipusDao.class);
        registerDaoClass(PartnerDao.class);
        registerDaoClass(PartnerKepDao.class);
        registerDaoClass(TelephelyDao.class);
        registerDaoClass(MunkaEszkozDao.class);
        registerDaoClass(MunkaDao.class);
        registerDaoClass(MunkaKepDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
