package com.schonherz.dbentities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MunkaEszkozok.
 */
public class MunkaEszkoz {

    private Long munkaEszkozID;
    private String munkaEszkozNev;
    private Long munkaEszkozAr;

    public MunkaEszkoz() {
    }

    public MunkaEszkoz(Long munkaEszkozID) {
        this.munkaEszkozID = munkaEszkozID;
    }

    public MunkaEszkoz(Long munkaEszkozID, String munkaEszkozNev, Long munkaEszkozAr) {
        this.munkaEszkozID = munkaEszkozID;
        this.munkaEszkozNev = munkaEszkozNev;
        this.munkaEszkozAr = munkaEszkozAr;
    }

    public Long getMunkaEszkozID() {
        return munkaEszkozID;
    }

    public void setMunkaEszkozID(Long munkaEszkozID) {
        this.munkaEszkozID = munkaEszkozID;
    }

    public String getMunkaEszkozNev() {
        return munkaEszkozNev;
    }

    public void setMunkaEszkozNev(String munkaEszkozNev) {
        this.munkaEszkozNev = munkaEszkozNev;
    }

    public Long getMunkaEszkozAr() {
        return munkaEszkozAr;
    }

    public void setMunkaEszkozAr(Long munkaEszkozAr) {
        this.munkaEszkozAr = munkaEszkozAr;
    }

}
