package com.schonherz.dbentities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PushMessages.
 */
public class PushMessage {

    private Long pushMessageID;
    private String pushMessageText;
    private String pushMessageDate;

    public PushMessage() {
    }

    public PushMessage(Long pushMessageID) {
        this.pushMessageID = pushMessageID;
    }

    public PushMessage(Long pushMessageID, String pushMessageText, String pushMessageDate) {
        this.pushMessageID = pushMessageID;
        this.pushMessageText = pushMessageText;
        this.pushMessageDate = pushMessageDate;
    }

    public Long getPushMessageID() {
        return pushMessageID;
    }

    public void setPushMessageID(Long pushMessageID) {
        this.pushMessageID = pushMessageID;
    }

    public String getPushMessageText() {
        return pushMessageText;
    }

    public void setPushMessageText(String pushMessageText) {
        this.pushMessageText = pushMessageText;
    }

    public String getPushMessageDate() {
        return pushMessageDate;
    }

    public void setPushMessageDate(String pushMessageDate) {
        this.pushMessageDate = pushMessageDate;
    }

}
